### ISSUE TITLE
建立socket中connected为false

### ISSUE THREAD

**Issue by shuxuezhang** [wxsocketio/wxapp-socket-io#10]
小程序代码如下
`var socket = io('http://192.168.3.88:8005/game',{query:param});`
`console.log('chat: ', socket)`
`socket.on('connect',function(data){
            console.log('connect',data)
        })
        socket.on('connected',function(data){
            console.log('connected',data)
        })
`
打印结果：（connected=false，   可是服务器任然是保持连接的）
`chat:  Socket {io: Manager, nsp: "/game", id: 0, connected: false, disconnected: true…}`

如何才能调用连接  并正确监听事件

**Comment by fanweixiao** [comment]
Please google 'nodejs eventloop'
